module.exports = [
  {
    id: 1,
    task: "Sign up for a Hookdeck account"
  },
  {
    id: 2,
    task: "Create a connection with a webhook provider using your API endpoint"
  },
  {
    id: 3,
    task: "Replace the endpoint in your provider's dashboard with the one generated by Hookdeck"
  }
];
